# 服务配置
server:
  host: 'localhost'
  port: 8020

# redis配置
redis:
  host: '192.168.133.181'
  port: 6379
  username: 'default'
  password: 522123
  db: 0

# 向外发起的http请求配置
http:
  baseURL: ''
  timeout: 5000

# 日志打印配置
winston:
  level: 'debug'
  dirname: 'log'
  filename: '%DATE%.log'
  datePattern: 'YYYY-MM-DD'
  maxSize: '1M'
